<?php
	class model_customer_address{
		public $fields= array();
		public $nullable= array();
		public $default_value= array();
		public $ID= 0;
		public $KEY= "";

		function model_customer_address($ID=0){
			$this->ID = $ID;
			$this->KEY = "id";
			$this->fields["id"]="int(11) unsigned";
			$this->nullable["id"]="NO";
			$this->default_value["id"]="";
			$this->fields["customer_id"]="int(11)";
			$this->nullable["customer_id"]="NO";
			$this->default_value["customer_id"]="";
			$this->fields["default_address"]="int(11)";
			$this->nullable["default_address"]="NO";
			$this->default_value["default_address"]="";
			$this->fields["first_name"]="varchar(50)";
			$this->nullable["first_name"]="NO";
			$this->default_value["first_name"]="";
			$this->fields["last_name"]="varchar(50)";
			$this->nullable["last_name"]="NO";
			$this->default_value["last_name"]="";
			$this->fields["phone"]="varchar(20)";
			$this->nullable["phone"]="NO";
			$this->default_value["phone"]="";
			$this->fields["email"]="varchar(100)";
			$this->nullable["email"]="NO";
			$this->default_value["email"]="";
			$this->fields["line1"]="varchar(500)";
			$this->nullable["line1"]="NO";
			$this->default_value["line1"]="";
			$this->fields["line2"]="varchar(500)";
			$this->nullable["line2"]="NO";
			$this->default_value["line2"]="";
			$this->fields["zipcode"]="varchar(20)";
			$this->nullable["zipcode"]="NO";
			$this->default_value["zipcode"]="";
			$this->fields["city"]="varchar(100)";
			$this->nullable["city"]="NO";
			$this->default_value["city"]="";
			$this->fields["state_id"]="int(11)";
			$this->nullable["state_id"]="NO";
			$this->default_value["state_id"]="";
			$this->fields["address_type"]="enum('Home','Office','Other')";
			$this->nullable["address_type"]="NO";
			$this->default_value["address_type"]="Home";
			$this->fields["note"]="varchar(255)";
			$this->nullable["note"]="NO";
			$this->default_value["note"]="";
			$this->fields["latitude"]="varchar(50)";
			$this->nullable["latitude"]="NO";
			$this->default_value["latitude"]="";
			$this->fields["longitude"]="varchar(50)";
			$this->nullable["longitude"]="NO";
			$this->default_value["longitude"]="";
			$this->fields["google_address"]="varchar(255)";
			$this->nullable["google_address"]="NO";
			$this->default_value["google_address"]="";
			$this->fields["customer_address_register_date"]="varchar(50)";
			$this->nullable["customer_address_register_date"]="NO";
			$this->default_value["customer_address_register_date"]="";
			$this->fields["customer_address_update_date"]="varchar(100)";
			$this->nullable["customer_address_update_date"]="NO";
			$this->default_value["customer_address_update_date"]="";
			$this->fields["updated_from"]="enum('Web','Android','Iphone','Admin')";
			$this->nullable["updated_from"]="NO";
			$this->default_value["updated_from"]="Web";
			$this->fields["ip_address"]="varbinary(45)";
			$this->nullable["ip_address"]="NO";
			$this->default_value["ip_address"]="";
		}
	}
?>